import {StyleSheet, StatusBar} from 'react-native';
import {COLOR, COMMON, FONTSIZE} from '../../constants';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLOR.bgColor__Main,
    paddingHorizontal: 10,
    position: 'relative',
  },
  wrapper: {
    minHeight: 50,
    width: '100%',
    paddingHorizontal: COMMON.paddingHorizital,
  },
  Header: {
    minHeight: 50,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: StatusBar.currentHeight,
    alignItems: 'center',
  },
  wrapperEarnMore: {
    flexDirection: 'row',
    minHeight: 100,
    width: '100%',
    marginTop: COMMON.spaceItem,
    position: 'relative',
    // left: 100,
  },
  avatar: {
    marginVertical: COMMON.spaceItem,
    height: 20,
    width: 20,
    borderRadius: 5,
    resizeMode: 'contain',
  },

  logo: {
    height: 115,
    width: 61,
    transform: [{rotate: '15deg'}],
  },
  wrapperUser: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userImages: {
    height: 50,
    width: 50,
    borderRadius: 25,
    resizeMode: 'contain',
    marginRight: 15,
  },
  txtPrimary: {
    fontSize: FONTSIZE.textFontSecondary,
    color: COLOR.txtColor__Black,
    fontWeight: 'bold',
  },
  txtMorePeople: {
    marginVertical: COMMON.spaceItem,
    padding: 2,
    color: COLOR.txtColor__White,
    fontSize: 12,
    backgroundColor: COLOR.bgColor__Main,
    borderRadius: 5,
  },
  sectionTitle: {
    marginLeft: 20,
  },
  wrapperPoints: {
    borderWidth: 1,
    borderRadius: COMMON.radiusPrimary,
    borderColor: COLOR.bgColor__Black,
    flexDirection: 'row',
    minWidth: 85,
    minHeight: 30,
    alignItems: 'center',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  txtSecondary: {
    fontSize: FONTSIZE.textFontPrimary,
    fontWeight: 'bold',
    color: COLOR.txtColor__Black,
  },
  Actions: {
    backgroundColor: COLOR.bgColor__White,
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: COMMON.radiusTertiary,
    marginTop: 5,
  },
  sectionGroup: {
    marginVertical: 20,
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  sectionList: {
    marginTop: 20,
    flex: 1,
    backgroundColor: COLOR.bgColor__White,
    paddingVertical: 10,
    paddingHorizontal: COMMON.paddingHorizital,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
  },
  sectionItem: {
    width: '100%',
    minHeight: 170,
    backgroundColor: COLOR.bgColor__Main_3,
    borderRadius: COMMON.radiusPrimary,
    padding: 20,
    marginBottom: 16,
    shadowColor: COLOR.bgColor__Black,
    shadowOffset: {
      width: 10,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  btnJoin: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 50,
    backgroundColor: COLOR.bgColor__Main,
    paddingHorizontal: 32,
    paddingVertical: 6,
    borderRadius: 10,
    marginLeft: 8,
  },
});

export {styles as HomeCss};
